name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  compile:
    name: Run Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ./postgres_cron/Dockerfile
          # options: -v ${{ github.workspace }}:/var/www
          run: |
            -d ramazanpolat/postgres_cron:15
